
name: goreleaser

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run release linux
        run: | 
          GOOS="linux" go build ./cmd/sqlc/. -o build/linux
          GOOS="darwin" go build ./cmd/sqlc/. -o build/mac
          GOOS=darwin GOARCH=arm64 go build ./cmd/sqlc/. -o build/mac-arm
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/**