name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.17
          dest: build
          prefix: sqlc
          targets: linux/amd64,darwin/amd64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          pkg: cmd/sqlc
      - run: |
          mv ./build/sqlc-darwin-10.16-amd64 ./build/sqlc-darwin-amd64
          mv ./build/sqlc-darwin-10.16-arm64 ./build/sqlc-darwin-arm64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          automatic_release_tag: "latest"
          files: |
            build/**