
name: goreleaser

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Run release linux
        run: | 
          CGO_ENABLED=1 GOOS="linux" go build -o ./build/linux-amd64/sqlc ./cmd/sqlc/. 
          CGO_ENABLED=1  GOOS="darwin" go build -o ./build/darwin-amd64/sqlc ./cmd/sqlc/. 
          CGO_ENABLED=1  GOOS=darwin GOARCH=arm64  go build -o ./build/darwin-arm64/sqlc ./cmd/sqlc/. 
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/**